defmodule UrlList do
  @moduledoc false

  def get do
    [
      "http://myoujijiten.web.fc2.com/a1.html",
      "http://myoujijiten.web.fc2.com/a2.html",
      "http://myoujijiten.web.fc2.com/i1.html",
      "http://myoujijiten.web.fc2.com/i2.html",
      "http://myoujijiten.web.fc2.com/i3.html",
#      "http://myoujijiten.web.fc2.com/u1.html",
#      "http://myoujijiten.web.fc2.com/u2.html",
#      "http://myoujijiten.web.fc2.com/e.html",
#      "http://myoujijiten.web.fc2.com/o1.html",
#      "http://myoujijiten.web.fc2.com/o2.html",
#      "http://myoujijiten.web.fc2.com/ka1.html",
#      "http://myoujijiten.web.fc2.com/ka2.html",
#      "http://myoujijiten.web.fc2.com/ka3.html",
#      "http://myoujijiten.web.fc2.com/ka4.html",
#      "http://myoujijiten.web.fc2.com/ki1.html",
#      "http://myoujijiten.web.fc2.com/ki2.html",
#      "http://myoujijiten.web.fc2.com/ku1.html",
#      "http://myoujijiten.web.fc2.com/ku2.html",
#      "http://myoujijiten.web.fc2.com/ke.html",
#      "http://myoujijiten.web.fc2.com/ko1.html",
#      "http://myoujijiten.web.fc2.com/ko2.html",
#      "http://myoujijiten.web.fc2.com/sa1.html",
#      "http://myoujijiten.web.fc2.com/sa2.html",
#      "http://myoujijiten.web.fc2.com/si1.html",
#      "http://myoujijiten.web.fc2.com/si2.html",
#      "http://myoujijiten.web.fc2.com/si3.html",
#      "http://myoujijiten.web.fc2.com/su.html",
#      "http://myoujijiten.web.fc2.com/se.html",
#      "http://myoujijiten.web.fc2.com/so.html",
#      "http://myoujijiten.web.fc2.com/ta1.html",
#      "http://myoujijiten.web.fc2.com/ta2.html",
#      "http://myoujijiten.web.fc2.com/ta3.html",
#      "http://myoujijiten.web.fc2.com/ti.html",
#      "http://myoujijiten.web.fc2.com/tu.html",
#      "http://myoujijiten.web.fc2.com/te.html",
#      "http://myoujijiten.web.fc2.com/to1.html",
#      "http://myoujijiten.web.fc2.com/to2.html",
#      "http://myoujijiten.web.fc2.com/na1.html",
#      "http://myoujijiten.web.fc2.com/na2.html",
#      "http://myoujijiten.web.fc2.com/ni.html",
#      "http://myoujijiten.web.fc2.com/nuneno.html",
#      "http://myoujijiten.web.fc2.com/ha1.html",
#      "http://myoujijiten.web.fc2.com/ha2.html",
#      "http://myoujijiten.web.fc2.com/hi1.html",
#      "http://myoujijiten.web.fc2.com/hi2.html",
#      "http://myoujijiten.web.fc2.com/hu.html",
#      "http://myoujijiten.web.fc2.com/heho.html",
#      "http://myoujijiten.web.fc2.com/ma1.html",
#      "http://myoujijiten.web.fc2.com/ma2.html",
#      "http://myoujijiten.web.fc2.com/mi1.html",
#      "http://myoujijiten.web.fc2.com/mi1.html",
#      "http://myoujijiten.web.fc2.com/mume.html",
#      "http://myoujijiten.web.fc2.com/mo.html",
#      "http://myoujijiten.web.fc2.com/ya.html",
#      "http://myoujijiten.web.fc2.com/yuyo.html",
#      "http://myoujijiten.web.fc2.com/rawagyou.html"
    ]
  end
end
